sensor:
  # EsPresence
  - platform: mqtt_room
    device_id: "iBeacon:9db64fee-xxxx-xxxx-xxxx-xxxx6d332312-100-1"
    name: "Pixel 4XL BLE"
    state_topic: "espresense/rooms"
    timeout: 60
    away_timeout: 60

  - platform: mqtt_room
    device_id: "iBeacon:22d06b50-xxxx-xxxx-xxxx-xxxxf113429_100_1"
    name: "Pixel 6PRO BLE"
    state_topic: "espresense/rooms"
    timeout: 60
    away_timeout: 60
